### ISSUE TITLE
did not work correctly. incoming TLS packets are lost, if they appear more than one in single api call.

### ISSUE THREAD

**Issue by rupicii** [kashifrazzaqui/sslfacade#1]
anyway as API aproach GREAT IDEA, but implementation sucks!
## check out this:

public interface EazySslOwner {
  public void incoming(ByteBuffer data);
  public boolean outgoing(ByteBuffer data);
  public void handshaked(SSLSession sess);
## }

public class EazySsl {
  private EazySslOwner owner;
  private SSLEngine    e;
  private boolean      notify;
  private ByteBuffer   partial, io;
  private ByteBuffer   empty = ByteBuffer.allocate(1);

  public EazySsl(SSLContext ctx, EazySslOwner owner) {
    e = ctx.createSSLEngine();
    e.setUseClientMode(false);
    e.setNeedClientAuth(true);
    e.setEnableSessionCreation(true); //???
    this.owner = owner;
    partial = ByteBuffer.allocate(e.getSession().getApplicationBufferSize() + 8192);
    io = ByteBuffer.allocate(e.getSession().getPacketBufferSize());
  }

  public void outgoing(ByteBuffer data) throws Exception {
    while (data.remaining() > 0) send(data);
  }

  public void incoming(ByteBuffer data) throws Exception {
    partial.put(data);
    partial.flip();
    while (partial.remaining() > 0) {
      io.clear();
      processWrap();
      SSLEngineResult res = e.unwrap(partial, io);
      if (res.getStatus() == SSLEngineResult.Status.BUFFER_UNDERFLOW) break;
      runDelegatedTasks(res);
      io.flip();
      if (io.remaining() == 0) continue;
      if (!notify) {
        owner.handshaked(e.getSession());
        notify = true;
      }
      owner.incoming(io);
    }
    processWrap();
    partial.compact();
  }

  private void send(ByteBuffer data) throws Exception {
    io.clear();
    SSLEngineResult res = e.wrap(data, io);
    runDelegatedTasks(res);
    io.flip();
    if (io.remaining() == 0) return;
    ByteBuffer copy = ByteBuffer.allocate(io.remaining());
    copy.put(io);
    copy.flip();
    owner.outgoing(copy);
  }

  private void processWrap() throws Exception {
    while (e.getHandshakeStatus() == SSLEngineResult.HandshakeStatus.NEED_WRAP)
      send(empty);
  }

  private void runDelegatedTasks(SSLEngineResult result) throws Exception {
    if (result.getHandshakeStatus() != HandshakeStatus.NEED_TASK) return;
    Runnable runnable;
    while ((runnable = e.getDelegatedTask()) != null)
      runnable.run();
  }
## }

the specific thing ir 8192 extra buffer space - amount of physical buffer for incoming network traffic in server, where i use this code.

**Comment by kashifrazzaqui** [comment]
Hey, you seem not to be using sslfacade and instead using SSLEngine directly, try using SSLFacade it should work.
