### ISSUE TITLE
Received fatal alert: bad_record_mac

### ISSUE THREAD

**Issue by tywo45** [kashifrazzaqui/sslfacade#5]
Hi, I am an user of sslfacade, i some times getting a "javax.net.ssl.SSLException: Received fatal alert: bad_record_mac"  error when send msg after ssl shakehandcompleted. do you have the same problem?

Thanks very much!

**Comment by kashifrazzaqui** [comment]
No, never had that issue. Have you had a look at this - https://github.com/openssl/openssl/issues/1866

**Comment by tywo45** [comment]
sorry! it is my own error, now ,it works well!
thanks your code!
